# docker-compose.yml

services:
  django_app:
    build: .
    volumes:
      - .:/app
      # اتصال ولوم کش pip به مسیر کش در کانتینر
      - pip-cache:/root/.cache/pip
    depends_on:
      - summarizer_app

  summarizer_app:
    build: ./summarizer_service
    volumes:
      - ./summarizer_service:/app
      # اتصال ولوم کش pip و huggingface به این سرویس
      - pip-cache:/root/.cache/pip
      - huggingface-cache:/root/.cache/huggingface
    
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # دسترسی nginx به فایل‌های استاتیک برای سرویس‌دهی مستقیم
      - .:/app 
    depends_on:
      - django_app
      - summarizer_app

# تعریف ولوم‌های نام‌گذاری شده در اینجا
# این ولوم‌ها توسط داکر مدیریت شده و حتی پس از خاموش شدن کانتینرها باقی می‌مانند
volumes:
  pip-cache:
  huggingface-cache: