services:
  django_app:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - summarizer_app

  summarizer_app:
    build: ./summarizer_service
    volumes:
      - ./summarizer_service:/app
      - pip-cache:/root/.cache/pip
      - huggingface-cache:/root/.cache/huggingface

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8087:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - django_app
      - summarizer_app

volumes:
  pip-cache:
  huggingface-cache:
  static_volume:
  media_volume: