# Generated by Django 5.2.4 on 2025-08-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام کامل")),
                ("title", models.CharField(max_length=100, verbose_name="عنوان شغلی")),
                ("bio", models.TextField(verbose_name="بیوگرافی")),
                (
                    "photo",
                    models.ImageField(upload_to="team_photos/", verbose_name="عکس"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "linkedin_url",
                    models.URLField(blank=True, null=True, verbose_name="لینک لینکدین"),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="لینک گیت\u200cهاب"
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        to="portfolio.technology",
                        verbose_name="مهارت\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "عضو تیم",
                "verbose_name_plural": "اعضای تیم",
            },
        ),
    ]
