# Generated by Django 5.2.4 on 2025-08-04 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام سرویس")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="آیکون",
                    ),
                ),
            ],
            options={
                "verbose_name": "سرویس",
                "verbose_name_plural": "سرویس\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام تکنولوژی")),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="technologies/",
                        verbose_name="آیکون",
                    ),
                ),
            ],
            options={
                "verbose_name": "تکنولوژی",
                "verbose_name_plural": "تکنولوژی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان پروژه")),
                ("description", models.TextField(verbose_name="توضیحات کوتاه")),
                (
                    "image",
                    models.ImageField(upload_to="projects/", verbose_name="تصویر اصلی"),
                ),
                (
                    "case_study_content",
                    models.TextField(verbose_name="محتوای مطالعه موردی"),
                ),
                (
                    "live_demo_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="لینک دموی زنده"
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        to="portfolio.service", verbose_name="سرویس\u200cهای ارائه شده"
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        to="portfolio.technology",
                        verbose_name="تکنولوژی\u200cهای استفاده شده",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروژه",
                "verbose_name_plural": "پروژه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=100, verbose_name="نام مشتری"),
                ),
                (
                    "client_title",
                    models.CharField(max_length=100, verbose_name="عنوان شغلی مشتری"),
                ),
                ("quote", models.TextField(verbose_name="نقل قول")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="portfolio.project",
                        verbose_name="پروژه مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "گواهی\u200cنامه",
                "verbose_name_plural": "گواهی\u200cنامه\u200cها",
            },
        ),
    ]
